config/routes.rb
Rails.application.routes.draw do
  root "payrol#index"
  post '/import_data' => "payrol#generate_data"
  get '/show' => 'payrol#show'
  post '/download_slip/:id' => "payrol#download_slip"
  post '/mail_pay_slip/:id' => "payrol#mail_payslip"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :payrols
  has_many :employees
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :company, optional: true
  has_many :salary_details, dependent: :destroy
end

app/models/payrol.rb
class Payrol < ApplicationRecord
  has_many :salary_details, dependent: :destroy
end

app/models/payslip_pdf.rb
require "render_anywhere"

class PayslipPdf
  include RenderAnywhere

  def initialize(payslip)
    @payslip = payslip
  end

  def to_pdf
    kit = PDFKit.new(as_html, page_size: 'A4')
    kit.to_file("#{Rails.root}/public/payslip.pdf")
  end

  def filename
    "Payslip #{payslip.id}.pdf"
  end

  private

    attr_reader :payslip

    def as_html
      render template: "payrol/download_slip",layout: "payslip_pdf", locals: { payslip: payslip }
    end
end

app/models/salary_detail.rb
class SalaryDetail < ApplicationRecord
  belongs_to :employee
  belongs_to :payrol
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/payrol_controller.rb
class PayrolController < ApplicationController
  require 'roo'

  def index
  end

  def generate_data
    begin
      sheet = Roo::Excelx.new(params[:file].path)
      SaveExcelData.new(sheet).call
      redirect_to show_path
      flash[:success] = "Nice Your Excel Sheet data is saved Sucessfully !!"
    rescue Exception => e
      redirect_to root_path
      flash[:danger] = "Please Upload Excelx file"
    end
  end

  def show
    @salary_details = SalaryDetail.includes(:employee).includes(:payrol)
  end

  def download_slip
    download_pdf
  end

  def mail_payslip
    # Sidekiq::Client.enqueue_to_in("default",Time.now, SendPayslipWorker,params[:id])
    begin
      PayslipMailer.payslip_send(params[:id]).deliver_now
      redirect_to show_path
      flash[:success] = "Pay Slip send to your email. Thank You !!"
    rescue Exception => e
      redirect_to show_path
      flash[:danger] = "Plese try again..!"
    end
  end

  private

  def payslip_pdf
    @salary_detail = SalaryDetail.includes(:employee).includes(:payrol).find_by(id: params[:id])
    PayslipPdf.new(@salary_detail)
  end

  def download_pdf
    send_file( payslip_pdf.to_pdf,filename: payslip_pdf.filename, type: "application/pdf", :disposition => 'attachment', :url_based_filename => false )
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Payroll</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/payslip_pdf.erb
<!DOCTYPE html>
<html>
<head>
  <title>PaySlip</title>
  <style>
    <%= Rails.application.assets.find_asset('application.scss').to_s %>
  </style>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/payrol/_payrol_list.html.erb
<table id="payroll_table" class="table">
  <tr >
    <th>Sr_No</th>
    <th>Emp_ID</th>
    <th>Name</th>
    <th>Designation</th>
    <th>Department</th>
    <th>Payroll Month</th>
    <th>Total Earning</th>
    <th>Deducted Amount</th>
    <th>Pay Amount</th>
    <th>Click to Choose</th>
  </tr>

  <%@salary_details.each do |salary_detail|%>
     <td><%= salary_detail.id %></td>
     <td><%= salary_detail.employee.emp_id %></td>
     <td><%= salary_detail.employee.name %></td>
     <td><%= salary_detail.employee.designation %></td>
     <td><%= salary_detail.employee.department %></td>
     <td><%= salary_detail.payrol.month %></td>
     <td><%= salary_detail.total_earning %></td>
     <td><%= salary_detail.total_deduction %></td>
     <td><%= salary_detail.total_paid_amount %></td>
     <td>
       <%= link_to "Download PaySlip","/download_slip/#{salary_detail.id}", class: "download_slip", method: :post%>
       <%= link_to "Email PaySlip" ,"/mail_pay_slip/#{salary_detail.id}",class: "mail_slip", method: :post %>
     </td>
   </tr>
  <%end%>
</table>

app/views/payrol/download_slip.html.erb
<h2>COMPLITECH SOLUTIONS PRIVATE LIMITED</h2>
<h3>Parul Nagar Society, Ahmedabad, Gujarat - 380061
CIN:U72900GJ2007PTC051398</h3>

<h4>Payslip for the Month of <%=payslip.payrol.month%>, <%=payslip.created_at.year%></h4>

<div class="container">
  <div class="left">
    <p><b>Employee ID</b> : <%=payslip.employee.emp_id%><p><br>
    <p><b>Name</b> : <%=payslip.employee.name%></p><br>
    <p><b>Designation</b> : <%=payslip.employee.designation%></p><br>
    <p><b>Department</b> : <%=payslip.employee.department%></p><br>
    <p><b>Effective Working Day</b> : <%=payslip.working_days%></p><br>
    <p><b>Account No</b> : <%=payslip.employee.account_no%></p><br>
    <p><b>Pan No</b> : <%=payslip.employee.designation%></p><br>
    <p><b>PF No</b> : <%=payslip.employee.department%></p><br>
  </div>

  <div class="salary">
    <p><b>Basic</b> : <%=payslip.basic%></p> <br>
    <p><b>PF</b> : <%=payslip.pf%></p><br>
    <p><b>HRA</b> : <%=payslip.hra%></p><br>
    <p><b>Incentives</b> : <%=payslip.incentives%></p><br>
    <p><b>Pf_deduction</b> : <%=payslip.pf_deduction%></p><br>
    <p><b>Esi_deduction</b> : <%=payslip.esi_deduction%></p><br>
    <p><b>Tds_deduction</b> : <%=payslip.tds_deduction%></p><br>
    <p><b>TOTAL EARNING</b> : <%=payslip.total_earning%></p><br>
    <p><b>TOTAL DEDUCTION</b> : <%=payslip.total_deduction%></p><br>
  </div>
</div>

<div class="total">
  <p><b>Net Pay for the Month :  <%=payslip.total_paid_amount%></b></p>
</div>

app/views/payrol/index.html.erb
<% if flash[:success] %>
 <div class = "alert alert-success flash-alert">
   <%= flash[:success] %>
 </div>
<% elsif flash[:danger]%>
 <div class = "alert alert-danger flash-alert" >
   <%= flash[:danger] %>
 </div>
<% end %>
<h1>Company Payroll System</h1>
<h2>Please upload excel sheet</h2>

<%= form_tag import_data_path, multipart: true do %>
  <%= file_field_tag :file, id: "payroll-file"%>
  <%= submit_tag "Upload" %>
<% end %>

app/views/payrol/show.html.erb
<% if flash[:success] %>
 <div class = "alert alert-success flash-alert">
   <%= flash[:success] %>
 </div>
<% elsif flash[:danger]%>
 <div class = "alert alert-danger flash-alert" >
   <%= flash[:danger] %>
 </div>
<% end %>
<h2>Employee Payroll</h2>
<%= render 'payrol_list'%>